name: JunaGeotagger
options:
  bundleIdPrefix: com.aumosita
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: false
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  JunaGeotagger:
    type: application
    platform: macOS
    sources:
      - path: JunaGeotagger
        excludes:
          - "Resources/**"
    resources:
      - path: JunaGeotagger/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aumosita.JunaGeotagger
        PRODUCT_NAME: Juna Geotagger
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "Juna Geotagger"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.photography"
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
